/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forms;

/**
 *
 * @author Janaina & Roberto
 */
public class frmEquipe extends javax.swing.JFrame {

    /**
     * Creates new form FormSobre
     */
    
    private static frmEquipe instance;
    
    public static frmEquipe getInstance()
    {
        if(instance == null)
      {
        instance = new frmEquipe();
        
      }
       
      return instance;
        
    }
    
    frmEquipe() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Sobre :.");
        setResizable(false);

        jTextArea.setEditable(false);
        jTextArea.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea.setRows(5);
        jTextArea.setText("\t\t................................\n\t\t: EQUIPE do Projeto de Sistema :\n\t\t................................\n_____________________________________________________________________\n\tGERENTE de PROJETO:\n\t\t\t\t- Alexandre;\n_____________________________________________________________________\n\n\tANÁLISE:\n\t\t\t\t- Bestriz;\n\t\t\t\t- Letícia;\t\n\t\t\t\t- Pâmela;\n\t\t\t\t- Sâmia;\n_____________________________________________________________________\n\t\n\tBANCO DE DADOS:\n\t\t\t\t- Ewerton;\t\t\n\t\t\t\t- Fábio;\n\t\t\t\t- Michele;\n\t\t\t\t- Vitor Fabbro;\n\t\t\t\t- Washington\n_____________________________________________________________________\n\n\tGERENTE de DESENVOLVIMENTO:\n\t\t\t\t- Ewerton;\n_____________________________________________________________________\n\n\tDESENVOLVEDORES:\n\n\t\t[Requisito 1]\n\t\t\t\t- Jonatas;\n\t\t\t\t- Luis;\n\t\t\t\t- Tainá;\n\n\t\t[Requisito 2]\n\t\t\t\t- Cristiane;\n\t\t\t\t- Jéssica;\n\t\t\t\t- Moisés;\n\n\t\t[Requisito 3]\n\t\t\t\t- Alexandre;\n\t\t\t\t- Janaina;\n\t\t\t\t- Pedro;\n\t\t\t\t- Roberto;\n\t\n\t\t[Requisito 4]\n\t\t\t\t- Anderson;\n\t\t\t\t- Lucas;\n\t\t\t\t- Vitor Ciudim;\n_____________________________________________________________________\n\n\tTESTERS:\n\t\t\t\t- Beatriz;\n\t\t\t\t- Jonatas;\n\t\t\t\t- Pâmela;\n\t\t\t\t- Pedro;\n_____________________________________________________________________");
        jTextArea.setAutoscrolls(false);
        jTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEquipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
