/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forms;

import utils.AceitaNumeros;
import utils.AceitaStrings;
import utils.LimitarLetras;
import utils.LimitarNumeros;
import java.util.ArrayList;
import dao.IdiomaDAO;
import dto.Idioma;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Multas
 */
public class frmIdioma extends javax.swing.JFrame {

    /**
     * Creates new form frmIdioma
     */
    
    private IdiomaDAO idiomaDAO;

    private void preencheTabela() {
        ArrayList<Idioma> idioma = new ArrayList<Idioma>();
        idioma = this.idiomaDAO.getIdiomasByID();
        
        DefaultTableModel tabela = (DefaultTableModel) tbIdioma.getModel();
        tabela.setNumRows(0);
               
        //Verifica se retornou algum valor da consulta.
        if (idioma == null)
        {
            return;
        }
        
        //a verificacao assima é por que esse modelo de for(ForEach|For Aprimorado|Enhanced For)
        //não aceita uma lista nula.
        for (Idioma i : idioma) 
        {
            if (i != null) 
            {
                Object[] obj = new Object[]{
                    i.getI_ID(),
                    i.getI_Nome()
                };
                tabela.addRow(obj);
            }
        }
    }
    
    public frmIdioma() {
        initComponents();
        
        this.idiomaDAO = new IdiomaDAO();
        preencheTabela();

        txtID.setDocument(new LimitarNumeros(11));
        txtIdioma.setDocument(new AceitaStrings());
        txtIdioma.setDocument(new LimitarLetras(45));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOrdenar = new javax.swing.ButtonGroup();
        pnlIdioma = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblIdioma = new javax.swing.JLabel();
        txtIdioma = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rbID = new javax.swing.JRadioButton();
        rbIdioma = new javax.swing.JRadioButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIdioma = new javax.swing.JTable();
        btnInserir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Cadastro de Idiomas :.");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlIdioma.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Idiomas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), java.awt.Color.blue)); // NOI18N

        lblID.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblID.setText("ID:");

        txtID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFocusLost(evt);
            }
        });

        lblIdioma.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblIdioma.setText("Idioma:");

        txtIdioma.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtIdioma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdiomaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdiomaFocusLost(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenar por:"));

        rbID.setText("ID");
        rbID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbIDMouseClicked(evt);
            }
        });

        rbIdioma.setText("Idioma");
        rbIdioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbIdiomaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbID)
                    .addComponent(rbIdioma))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(rbIdioma))
        );

        javax.swing.GroupLayout pnlIdiomaLayout = new javax.swing.GroupLayout(pnlIdioma);
        pnlIdioma.setLayout(pnlIdiomaLayout);
        pnlIdiomaLayout.setHorizontalGroup(
            pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdiomaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblID)
                    .addComponent(lblIdioma))
                .addGap(18, 18, 18)
                .addGroup(pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlIdiomaLayout.setVerticalGroup(
            pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdiomaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlIdiomaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdioma)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
            .addGroup(pnlIdiomaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/korganizer.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button_cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tbIdioma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Idioma"
            }
        ));
        tbIdioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbIdiomaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbIdioma);

        btnInserir.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(pnlIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    int opcao = 0;
    
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        Idioma idioma = new Idioma();
        idioma.setI_ID(Integer.parseInt(txtID.getText()));

        int dialogButton = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o Idioma selecionado ?", "Warning", 0);// 0 = botão Sim e Não

        if (dialogButton == JOptionPane.YES_OPTION) {
            if (this.idiomaDAO.excluir(idioma) == true) {
                JOptionPane.showMessageDialog(null, "Idioma '" + txtIdioma.getText() + "' excluido com sucesso!");
                Limpar();
                Desabilitar();
                btnInserir.setEnabled(true);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
                btnCancelar.setEnabled(false);
                btnSalvar.setEnabled(false);
                
                rbID.setEnabled(true);
                rbIdioma.setEnabled(true);

                preencheTabela();
            } else {
                JOptionPane.showMessageDialog(null, "Não é possível excluir o idioma, pois há alunos ou professores vinculados!");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        opcao = 1;
        IdiomaDAO idiomaDAO = new IdiomaDAO();
                
        txtID.setText(String.valueOf(idiomaDAO.AutoIncID()));

        Habilitar();

        btnInserir.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        
        rbID.setEnabled(false);
        rbIdioma.setEnabled(false);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void rbIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbIDMouseClicked
        // TODO add your handling code here:
        btnInserir.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
        
        if (rbID.isSelected()) {
            ArrayList<Idioma> idioma = new ArrayList<Idioma>();
            idioma = this.idiomaDAO.getIdiomasByID();
            
            DefaultTableModel tabela = (DefaultTableModel) tbIdioma.getModel();
            tabela.setNumRows(0);          

                for (Idioma i : idioma)
                {
                    if (i != null)
                    {
                        Object[] obj = new Object[]{
                            i.getI_ID(),
                            i.getI_Nome()
                        };
                        tabela.addRow(obj);
                    }
                }
            }
    }//GEN-LAST:event_rbIDMouseClicked

    private void rbIdiomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbIdiomaMouseClicked
        // TODO add your handling code here:
        btnInserir.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
        
        if (rbIdioma.isSelected()) {
            ArrayList<Idioma> idioma = new ArrayList<Idioma>();
            idioma = this.idiomaDAO.getIdiomasByNome();
            
            DefaultTableModel tabela = (DefaultTableModel) tbIdioma.getModel();
            tabela.setNumRows(0);

                for (Idioma i : idioma)
                {
                    if (i != null)
                    {
                        Object[] obj = new Object[]{
                            i.getI_ID(),
                            i.getI_Nome()
                        };
                        tabela.addRow(obj);
                    }
                }
            }
    }//GEN-LAST:event_rbIdiomaMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        opcao = 2;
        
        Habilitar();

        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        
        rbID.setEnabled(false);
        rbIdioma.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Limpar();
        
        btnInserir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
        
        rbID.setEnabled(true);
        rbIdioma.setEnabled(true);
        
        Desabilitar();
        txtIdioma.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (txtIdioma.getText().equals(""))
    {
        JOptionPane.showMessageDialog(null, "É necessário preencher o nome do Idioma ! ","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        txtIdioma.setBackground(java.awt.Color.RED);
        txtIdioma.requestFocus();
    }
    else
    {
        if (opcao == 1) 
        {
            Idioma cat = new Idioma();

            cat.setI_ID(Integer.parseInt(txtID.getText()));
            cat.setI_Nome(txtIdioma.getText().toUpperCase());
                    
            if (this.idiomaDAO.inserir(cat) == true)
            {
                String id = txtID.getText();                               
                String nome = txtIdioma.getText();
                JOptionPane.showMessageDialog(null, "Idioma '" + txtIdioma.getText() + "' adicionado com sucesso!");
                
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Erro ao adicionar Idioma!");
            }
        } 
        else if (opcao == 2) 
        {
            Idioma idioma = new Idioma();
            idioma.setI_ID(Integer.parseInt(txtID.getText()));
            idioma.setI_Nome(txtIdioma.getText().toUpperCase());

            if (this.idiomaDAO.editar(idioma) == true) 
            {
                JOptionPane.showMessageDialog(null, "Idioma modificado com sucesso!");
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Erro ao modificar Idioma!");
            }
        }
        preencheTabela();
        Limpar();
        Desabilitar();
        
        btnInserir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
        
        rbID.setEnabled(true);
        rbIdioma.setEnabled(true);
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Desabilitar();

        btnInserir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);

        txtID.setBackground(java.awt.Color.white);

        grupoOrdenar.add(rbID);
        grupoOrdenar.add(rbIdioma);

        rbID.setSelected(true);// inicia selecionado
    }//GEN-LAST:event_formWindowOpened

    private void tbIdiomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIdiomaMouseClicked
        // TODO add your handling code here:
        int linhaselecionada = tbIdioma.getSelectedRow(); //pega a linha selecionada
        
        txtID.setText(tbIdioma.getValueAt(linhaselecionada, 0).toString());
        txtIdioma.setText(tbIdioma.getValueAt(linhaselecionada, 1).toString());

        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(false);
        
        rbID.setEnabled(false);
        rbIdioma.setEnabled(false);
    }//GEN-LAST:event_tbIdiomaMouseClicked

    private void txtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusLost
        // TODO add your handling code here:
        txtID.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_txtIDFocusLost

    private void txtIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusGained
        // TODO add your handling code here:
        txtID.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_txtIDFocusGained

    private void txtIdiomaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdiomaFocusLost
        // TODO add your handling code here:
        txtIdioma.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_txtIdiomaFocusLost

    private void txtIdiomaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdiomaFocusGained
        // TODO add your handling code here:
        txtIdioma.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_txtIdiomaFocusGained
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIdioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIdioma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup grupoOrdenar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JPanel pnlIdioma;
    private javax.swing.JRadioButton rbID;
    private javax.swing.JRadioButton rbIdioma;
    private javax.swing.JTable tbIdioma;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIdioma;
    // End of variables declaration//GEN-END:variables

        
     public void Habilitar() {
        txtID.setEnabled(false);
        txtIdioma.setEnabled(true);
        txtIdioma.requestFocus();//recebe o foco
    }

    public void Desabilitar() {
        txtID.setEnabled(false);
        txtIdioma.setEnabled(false);
    }

    public void Limpar() {
        txtID.setText("");
        txtIdioma.setText("");
        txtIdioma.requestFocus();
    }
}
