/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import javax.swing.JOptionPane;
import utils.AceitaNumeros;
import dao.DisciplinaDAO;
import dto.Disciplina;
import dto.RelatorioDisciplina;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anderson
 */
public class frmRelatorioDisciplina extends javax.swing.JFrame {

  /**
   * Creates new form frmRelatorioDisciplina
   */
  public frmRelatorioDisciplina() {
    initComponents();
    txtProntuario.setDocument(new AceitaNumeros());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    groupAP = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    lblIdDisciplina = new javax.swing.JLabel();
    txtProntuario = new javax.swing.JTextField();
    rbtProfessor = new javax.swing.JRadioButton();
    rbtAluno = new javax.swing.JRadioButton();
    btnLocalizar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblRelatorio = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatório de Disciplina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), java.awt.Color.blue)); // NOI18N

    lblIdDisciplina.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
    lblIdDisciplina.setText("Prontuário:");

    txtProntuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
    txtProntuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtProntuarioActionPerformed(evt);
      }
    });

    groupAP.add(rbtProfessor);
    rbtProfessor.setSelected(true);
    rbtProfessor.setText("Professor");

    groupAP.add(rbtAluno);
    rbtAluno.setText("Aluno");

    btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
    btnLocalizar.setText("Pesquisar");
    btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLocalizarActionPerformed(evt);
      }
    });
    btnLocalizar.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        btnLocalizarKeyPressed(evt);
      }
    });

    tblRelatorio.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Prontuário", "Nome", "Disciplina"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tblRelatorio);
    if (tblRelatorio.getColumnModel().getColumnCount() > 0) {
      tblRelatorio.getColumnModel().getColumn(0).setResizable(false);
      tblRelatorio.getColumnModel().getColumn(0).setPreferredWidth(10);
      tblRelatorio.getColumnModel().getColumn(1).setResizable(false);
      tblRelatorio.getColumnModel().getColumn(1).setPreferredWidth(150);
      tblRelatorio.getColumnModel().getColumn(2).setResizable(false);
      tblRelatorio.getColumnModel().getColumn(2).setPreferredWidth(100);
    }

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(31, 31, 31)
        .addComponent(lblIdDisciplina)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(71, 71, 71)
        .addComponent(rbtProfessor)
        .addGap(26, 26, 26)
        .addComponent(rbtAluno)
        .addGap(34, 34, 34)
        .addComponent(btnLocalizar)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lblIdDisciplina, javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(txtProntuario, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(rbtProfessor, javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(rbtAluno, javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(btnLocalizar, javax.swing.GroupLayout.Alignment.CENTER))
        .addGap(11, 11, 11)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void txtProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProntuarioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtProntuarioActionPerformed

  private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
    if (!ValidarCampos())
      return;
    
    String tipo;
    String id;
    if (rbtProfessor.isSelected())
      tipo = "P";
    else
      tipo = "A";
    
    id = txtProntuario.getText();
    
    DisciplinaDAO dDao = new DisciplinaDAO();
    Disciplina d = dDao.getDisciplinaByID(Integer.parseInt(txtProntuario.getText()));
    
    if (d == null && !id.equals("0")){
      JOptionPane.showMessageDialog(null, "Disciplina não encontrada");
      return;
    }

    preencherTable(id, tipo);
   
  }//GEN-LAST:event_btnLocalizarActionPerformed

  private void btnLocalizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLocalizarKeyPressed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnLocalizarKeyPressed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(frmRelatorioDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(frmRelatorioDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(frmRelatorioDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(frmRelatorioDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new frmRelatorioDisciplina().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLocalizar;
  private javax.swing.ButtonGroup groupAP;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblIdDisciplina;
  private javax.swing.JRadioButton rbtAluno;
  private javax.swing.JRadioButton rbtProfessor;
  private javax.swing.JTable tblRelatorio;
  private javax.swing.JTextField txtProntuario;
  // End of variables declaration//GEN-END:variables

  private boolean ValidarCampos() {
    if (txtProntuario.getText().isEmpty()){
      JOptionPane.showMessageDialog(null, "Prontuário Inválido\nDigite '0' para todos");
      return false;
    }
    return true;
  }

  private void preencherTable(String id, String tipo) {
    
    DefaultTableModel jtblRelatorio = (DefaultTableModel) tblRelatorio.getModel();
    jtblRelatorio.setNumRows(0);
    
    DisciplinaDAO dDao = new DisciplinaDAO();
    ArrayList<RelatorioDisciplina> relatorio = new ArrayList<RelatorioDisciplina>();
    relatorio = dDao.getDisciplinaRelatorio(id, tipo);
    
    if (relatorio.size()== 0){
      JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado");
      return;
    }

    for (int i = 0; i < relatorio.size(); i++)
    {
      Object[] obj = new Object[]
      {
        relatorio.get(i).getProntuaio(),
        relatorio.get(i).getNome(),
        relatorio.get(i).getNomeDisciplina()        
      };
      jtblRelatorio.addRow(obj);
    }
  }
}
